

template = {'code' : 'code', 'location' : 'location', 'registered' : 'registered',
            'envelopes' : 'envelopes', 'valid' : 'valid',
            'Občanská demokratická strana' : 'Občanská demokratická strana',
            'Řád národa - Vlastenecká unie' : 'Řád národa - Vlastenecká unie',
            'CESTA ODPOVĚDNÉ SPOLEČNOSTI' : 'CESTA ODPOVĚDNÉ SPOLEČNOSTI',
            'Česká str.sociálně demokrat.' : 'Česká str.sociálně demokrat.',
            'Volte Pr.Blok www.cibulka.net' : 'Volte Pr.Blok www.cibulka.net',
            'Radostné Česko': 'Radostné Česko',
            'STAROSTOVÉ A NEZÁVISLÍ': 'STAROSTOVÉ A NEZÁVISLÍ',
            'Komunistická str.Čech a Moravy': 'Komunistická str.Čech a Moravy',
            'Strana zelených': 'Strana zelených',
            'ROZUMNÍ-stop migraci,diktát.EU': 'ROZUMNÍ-stop migraci,diktát.EU',
            'Společ.proti výst.v Prok.údolí': 'Společ.proti výst.v Prok.údolí',
            'Strana svobodných občanů': 'Strana svobodných občanů',
            'Blok proti islam.-Obran.domova': 'Blok proti islam.-Obran.domova',
            'Občanská demokratická aliance': 'Občanská demokratická aliance',
            'Česká pirátská strana': 'Česká pirátská strana',
            'OBČANÉ 2011-SPRAVEDL. PRO LIDI': 'OBČANÉ 2011-SPRAVEDL. PRO LIDI',
            'Unie H.A.V.E.L.': 'Unie H.A.V.E.L.',
            'Česká národní fronta': 'Česká národní fronta',
            'Referendum o Evropské unii': 'Referendum o Evropské unii',
            'TOP 09': 'TOP 09',
            'ANO 2011': 'ANO 2011',
            'Dobrá volba 2016': 'Dobrá volba 2016',
            'SPR-Republ.str.Čsl. M.Sládka': 'SPR-Republ.str.Čsl. M.Sládka',
            'Křesť.demokr.unie-Čs.str.lid.': 'Křesť.demokr.unie-Čs.str.lid.',
            'Česká strana národně sociální': 'Česká strana národně sociální',
            'REALISTÉ': 'REALISTÉ',
            'SPORTOVCI': 'SPORTOVCI',
            'Dělnic.str.sociální spravedl.': 'Dělnic.str.sociální spravedl.',
            'Svob.a př.dem.-T.Okamura (SPD)': 'Svob.a př.dem.-T.Okamura (SPD)',
            'Strana Práv Občanů': 'Strana Práv Občanů', 'Národ Sobě':'Národ Sobě'
            }
